// Mocks generated by Mockito 5.0.14 from annotations
// in apps/test/home_bloc.test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:apps/api/model/data.dart' as _i2;
import 'package:apps/api/vacination_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeData_0 extends _i1.Fake implements _i2.Data {}

/// A class which mocks [VacinationAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockVacinationAPI extends _i1.Mock implements _i3.VacinationAPI {
  MockVacinationAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Data> getBrazilTotal() =>
      (super.noSuchMethod(Invocation.method(#getBrazilTotal, []),
              returnValue: Future<_i2.Data>.value(_FakeData_0()))
          as _i4.Future<_i2.Data>);
  @override
  _i4.Future<_i2.Data> getData(String? code) =>
      (super.noSuchMethod(Invocation.method(#getData, [code]),
              returnValue: Future<_i2.Data>.value(_FakeData_0()))
          as _i4.Future<_i2.Data>);
  @override
  String toString() => super.toString();
}
